name: ci.yml
on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: ''
      - name: Build
        run: ./gradlew check

